// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzegmenesqndwtionxbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6ZWdtZW5lc3FuZHd0aW9ueGJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMDc4NDgsImV4cCI6MjA2Njg4Mzg0OH0.hfyifzMt6vvEcq-K_N7-nJDxGDuvhfwJwiZJIqoihAc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});